Repository josoavj/elasticsearch-nodejs-server, pull requests merged in 2024-07, with the labels that each got.

#3 refractor: test
  elasticsearch.js
Labels: good first issue

#4 refactor: Adding the http_ca certificate
  assets/http_ca.crt
  elasticsearch.js
Labels: enhancement

#5 SSL connection between elasticsearch cluster and NodeJS
  elasticsearch.js
  node_modules/@elastic/elasticsearch/tsconfig.json
Labels: bug, wontfix

#7 Update README.md
  README.md
Labels: documentation

#8 Elastic
  api
  elasticsearch.js
Labels: minor updates, feat

#9 fix: elasticsearch index data fixed
  elasticsearch.js
Labels: minor updates

#10 Elasticsearch client info
  README.md
  elasticsearch.js
Labels: minor updates

#11 refactor: Updating the elasticsearch index
  elasticsearch.js
Labels: minor updates

#14 refactor: Test d'accès aux données du serveur elasticsearch
  Back-end/elasticsearch.js
Labels: invalid, minor updates

#17 Elasticsearch
  .idea/.gitignore
  .idea/misc.xml
  .idea/modules.xml
  .idea/sfi.iml
  .idea/vcs.xml
  Back-end/elasticsearch.js
  Back-end/testElasticsearch.js
Labels: minor updates

#19 Update README.md
  README.md
Labels: documentation
